[build]
  functions = "netlify/functions"

[[redirects]]
  from = "/"
  to = "/profissional.html"
  status = 302

[[redirects]]
  from = "/index.html"
  to = "/profissional.html"
  status = 302

[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
